server:
  port: 8888

spring:
  cloud:
    config:
      server:
        native:
          search-locations: "classpath:/config/"
  profiles:
    active: native
#        git:
#          uri: https://github.com/rhirabay/spring-cloud-config-properties
