
spring:
  datasource:
    driver-class-name: "org.h2.Driver"
    url: "jdbc:h2:./h2db/sample"
    initialization-mode: always
    hikari:
      idle-timeout: 0
      register-mbeans: true
      maxLifetime: 31000
    type: "com.zaxxer.hikari.HikariDataSource"

logging:
  level:
    "com.zaxxer.hikari": INFO

management:
  endpoints:
    web:
      exposure:
        include: "prometheus"
  metrics:
    data:
      repository:
        autotime:
          # 自動でメトリクスを収集するかどうか？
          # falseを指定すると個別に「@Timed」アノテーションの付与が必要
          enabled: true
          # パーセンタイルも取得する
          percentiles: 0.5,0.99
        # メトリクス名を指定する
        metric-name: "spring.data.repository.invocations"
#  metrics:
#    distribution:
#      percentiles:
#        "spring.data.repository.invocations": 0.5,0.99

#      base-path: "/"
#  server:
#    port: 9990