
spring:
  datasource:
    driver-class-name: "org.h2.Driver"
    url: "jdbc:h2:./h2db/sample"
    initialization-mode: always
    hikari:
      idle-timeout: 0
      register-mbeans: true
      maxLifetime: 31000
    type: "com.zaxxer.hikari.HikariDataSource"

logging:
  level:
    "com.zaxxer.hikari": debug