opentracing:
  jaeger:
    udp-sender:
      host: localhost
      port: 6831
    rate-limiting-sampler:
      max-traces-per-second: 10

spring:
  datasource:
    # driver-class-name: "org.h2.Driver"
    driver-class-name: "io.opentracing.contrib.jdbc.TracingDriver"
    # url: "jdbc:h2:./h2db/sample"
    url: "jdbc:tracing:h2:./h2db/sample"
  application:
    name: jaeger-sample
