version: '2'
services:
  jeager:
    image: jaegertracing/all-in-one:1.32
    ports:
      - "6831:6831/udp" # accept jaeger.thrift over compact thrift protocol
      - "6832:6832/udp" # accept jaeger.thrift over binary thrift protocol
      - "5778:5778"     # serve configs
      - "16686:16686"   # serve frontend
      - "14250:14250"   # accept model.proto
      - "14268:14268"   # accept jaeger.thrift directly from clients
      - "14269:14269"   #
      - "9411:9411"     # Zipkin compatible endpoint (optional)
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: ":9411"