spring:
  redis:
    host: localhost
    port: 6379
  cloud:
    gateway:
      routes:
        # curl -X POST http://localhost:8080/validate/post -d '{"number":123,"key":"value"}' -H 'Content-Type: application/json' | jq
        - id: validate
          uri: "http://localhost:8080"
          predicates:
            - Path=/validate/**
          filters:
            - PrefixPath=/api
            - name: ValidateRequestBody
              args:
                roles: |
                  {"number":"^[0-9]+$"}
        - id: csrl
          uri: "http://localhost:8080"
          predicates:
            - Path=/csrl/**
          filters:
            - PrefixPath=/api
            - name: CurrentSessionRateLimit
              args:
                limit: 1
        - id: custom
          uri: "http://localhost:8080"
          predicates:
            - Path=/custom/**
          filters:
            - PrefixPath=/api
            - name: Custom
              args:
                message: "hello world"
        - id: custom2
          uri: "http://localhost:8080"
          predicates:
            - Path=/custom2/**
          filters:
            - PrefixPath=/api
            - name: Custom
              args:
                message: "hello world 2"
        - id: ratelimit
          uri: "http://localhost:8080"
          predicates:
            - Path=/ratelimit/**
          filters:
            - PrefixPath=/api
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 10
        - id: circuitbreaker
          uri: "http://localhost:8080"
          predicates:
            - Path=/circuitbreaker/**
          filters:
            - PrefixPath=/api/randomSleep
            - name: CircuitBreaker
              args:
                name: myCircuitBreaker
                fallbackUri: forward:/api/fallback
        - id: default
          uri: "http://localhost:8080"
          predicates:
            - Path=/**
          filters:
            - PrefixPath=/api
  profiles:
    active: standalone

logging:
  level:
    root: info
